language: ruby
rvm:
- 2.3.1
env:
  global:
    secure: "ND69gJ0h5JB0I7mogcjIwAr+3lc815M0L9i9xg7CKVdtMKyuLIT/QKoqAJ9ivnYCapnRrxweRco82VlrFz6hru5phhEiCHLLmdyYngZcjVOnTWVLanc9juQ+cz/65lqJl7MbwZxKbdurh4/2FzGoTCMdjIYzMDk+pT0hHHiZ+8p492mj0hdglGX1WfoQJvIsvR94jy+JEDsjzlB6odk+uhD2qlhK0/k2UDG8tlbEPp/zf2dvonhud3TmdvkiVTNKPS1kpB1BJCwkhNfg7ZRKkt0FMMR/g1GAfHlRE/FiUaVCyurUaUVnfAUvhuGZ28XhHotRCogP6YV6hkpWy7wyelool4c+CzSho4cdEwNFiNXME5wbpMUiZN5w9YTBBK11u2uPrhw2tUvJtjNQdvvKKdQw404hPcVaLsGaviK3G6qC1huo3kRQW51HgBF8J99+icCDgTyM+m+iJrQwCGU+darpv/ozpczoM9avE6EOF1Nu+35iRAdu5o4KR4k5EDf7AlXck1B0n5aAYj7t624cVKIF9vusOq7nmT63N8m37ZBWz09aAHasW0bm6ReB6+uOFM776Umh3/A6hr0zYrqiaQuk1zw2PNR5twvrqSLqEAwEK9ozROe3bWMdFlZhoCWNzaKNqMCt0O8B1k5xPClx3uhI63XeykxMWMDFLfvQNtw="
install: bundle
script:
- rake test
- rake build
deploy:
  provider: rubygems
  gem: minke
  on:
    repo: nicholasjackson/minke
  api_key:
    secure: NfDL67sdeJ0FOSYns+VKjPPk/ZAhJa/wpffw5RiXG94gst5XUtZauik1nVIrTpWYhw5e34hqHPH9mE+v8AkXQRmGyUkYbW+0ePFuqBHidsSFGUOzg3h0+wYrOkvA60REJAg1EM97IDx7PmhcxfO3NFsDvr6RKOXaNc3cLxmiIdD9PVktm75hk2BvoiuO3d12ph2Wr9RjSuidX/0z2H8oOdDs8e14x9QPqX3LuRiTe+A3h+hjZ1OhH9aT5blJ2ZI65iDMY1K6hzcDuUY7CzCbKZF2pPEkDgtT5FgRX1klu28Ehxebef/vvAFmOt5ztuXyE6nEdoI8NACE7XXQQC+6H5PzE6hWoHKk7/vMn5u2pdMRUykArAJ6++JxRSitaKSXn0xZfRKvszp00WhHiG4kPtQXgNKiJiuOKX9huy+gHssYfP3sxcd0LNrslnxaGRAn0igRHuBeaIi8kxL+03q1tCSjOcc6OV9qPIgZAiGUdeeolefrXFTovptcG5PiDzq6jJoQSO51kRMhG/XGfuf2T+vpl5ouT2dsYSz8qDchX5LEjcjuBXb3J1/Xz5s1oQjGI1w+bSrZ1OAFv0d5v8jcD9IyF4C7iVuqCtlc0bNkm9ZgwG+iHHj/SxezFPCttVFBS2or6YizA2xAONXkuy2g+yUDZplcX56fe0oIQsOJOjc=
