# Setup
title:        Minke
tagline:      Build tools and generators for your Î¼Services workflow.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Nic Jackson
  url:        http://github.com/nicholasjackson

# Gems
gems:
  - jekyll-paginate

#Others
encoding: utf-8
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

menus:
  main:
    - Home: /
    - Other: /
