namespace: 'github.com/nicholasjackson'
application_name: 'event-sauce'
docker_registry:
  url: <%= ENV['DOCKER_REGISTRY_URL'] %>
  user: <%= ENV['DOCKER_REGISTRY_USER'] %>
  password: <%= ENV['DOCKER_REGISTRY_PASS'] %>
  email: <%= ENV['DOCKER_REGISTRY_EMAIL'] %>
  namespace: <%= ENV['DOCKER_NAMESPACE'] %>
docker:
  build_image: [optional]
  build_docker_file: [optional]
  application_docker_file: './dockerfiles/event-sauce/Dockerfile'
  application_compose_file: './dockercompose/event-sauce/docker-compose.yml'
fetch:
  include: true
build:
  pre:
    tasks:
      -
    copy_assets:
      -
  docker:
    application_compose_file: './dockercompose/event-sauce/docker-compose.yml'
  post:
    tasks:
      -
    copy:
      -
        from: <%= "#{ENV['GOPATH']}/src/github.com/nicholasjackson/event-sauce/event-sauce" %>
        to: './docker/event-sauce'
      -
        from: './swagger_spec/swagger.yml'
        to: './dockerfile/event-sauce/swagger_spec/swagger.yml'
run:
  pre:
    consul_loader:
      config_file: './config.yml'
      url: http://<%= get_public_server_for 'test2:9500' %> # specifying the url as a coompose server name and private port will auto resolve
  docker:
    application_compose_file: './dockercompose/event-sauce/docker-compose-alternate.yml'
  post:
    tasks:
      - wait_for_elastic_search
cucumber:
  pre:
    consul_loader:
      config_file: './config.yml'
      url: http://<%= get_public_server_for 'consul:8500' %>
    health_check:
      url: http://<%= get_public_server_for 'test2:8001' %>/v1/health
  post:
    tasks:
      - 'wait_for_elastic_search'
